Loading the dataset

In [1]:
import pandas as pd

data = pd.read_csv(r"C:\Users\world\Desktop\ASU\Fall 2024\Data Mining\kmeans_data\data.csv", header=None)  
labels = pd.read_csv(r"C:\Users\world\Desktop\ASU\Fall 2024\Data Mining\kmeans_data\label.csv", header=None)  

Understanding the data

In [4]:
data.head()

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
0    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

   778  779  780  781  782  783  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 784 columns]

In [5]:
labels.head()

0
0  7
1  2
2  1
3  0
4  4

In [6]:
data.describe()

0        1        2        3        4        5        6        7    \
count  10000.0  10000.0  10000.0  10000.0  10000.0  10000.0  10000.0  10000.0   
mean       0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
std        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
25%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
50%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
75%        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
max        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

           8        9    ...           774           775           776  \
count  10000.0  10000.0  ...  10000.000000  10000.000000  10000.000000   
mean       0.0      0.0  ...      0.179300      0.163600      0.052600   
std        0.0      0.0  ...      5.674149      5.736072      2.420004   
min        0.0      0.0  ...      0.000000      0.000000      0.000000   
25%        0.0      0.0  ...      0.000000      0.000000      0.000000   
50%        0.0      0.0  ...      0.000000      0.000000      0.000000   
75%        0.0      0.0  ...      0.000000      0.000000      0.000000   
max        0.0      0.0  ...    253.000000    253.000000    156.000000   

              777      778      779      780      781      782      783  
count  10000.0000  10000.0  10000.0  10000.0  10000.0  10000.0  10000.0  
mean       0.0006      0.0      0.0      0.0      0.0      0.0      0.0  
std        0.0600      0.0      0.0      0.0      0.0      0.0      0.0  
min        0.0000      0.0      0.0      0.0      0.0      0.0      0.0  
25%        0.0000      0.0      0.0      0.0      0.0      0.0      0.0  
50%        0.0000      0.0      0.0      0.0      0.0      0.0      0.0  
75%        0.0000      0.0      0.0      0.0      0.0      0.0      0.0  
max        6.0000      0.0      0.0      0.0      0.0      0.0      0.0  

[8 rows x 784 columns]

In [7]:
labels[0].value_counts()

1    1135
2    1032
7    1028
3    1010
9    1009
4     982
0     980
8     974
6     958
5     892
Name: 0, dtype: int64

Defining the distance metrics

In [22]:
import numpy as np
import pandas as pd

# Define Euclidean Distance
def euclidean_distance(point1, point2):
    return np.sqrt(np.sum((point1 - point2) ** 2))

# Define 1 - Cosine Similarity
def cosine_distance(point1, point2):
    cosine_sim = np.dot(point1, point2) / (np.linalg.norm(point1) * np.linalg.norm(point2))
    return 1 - cosine_sim

# Define 1 - Generalized Jaccard Similarity
def jaccard_distance(point1, point2):
    intersection = np.sum(np.minimum(point1, point2))
    union = np.sum(np.maximum(point1, point2))
    return 1 - (intersection / union)

1. Basic K-Means Algorithm

In [23]:
#Basic k-Means Algorithm

# Initialize centroids randomly
def initialize_centroids(data, k):
    np.random.seed(42)
    random_indices = np.random.choice(data.shape[0], size=k, replace=False)
    return data[random_indices]

# Assign clusters based on the selected distance function
def assign_clusters(data, centroids, distance_function):
    clusters = []
    for point in data:
        distances = [distance_function(point, centroid) for centroid in centroids]
        clusters.append(np.argmin(distances))
    return np.array(clusters)

# Update centroids by calculating the mean of assigned points
def update_centroids(data, clusters, k):
    new_centroids = []
    for i in range(k):
        cluster_points = data[clusters == i]
        new_centroids.append(cluster_points.mean(axis=0) if len(cluster_points) > 0 else np.random.rand(data.shape[1]))
    return np.array(new_centroids)

# Main K-means function
def kmeans(data, k, distance_function, max_iters=100):
    centroids = initialize_centroids(data, k)
    for _ in range(max_iters):
        clusters = assign_clusters(data, centroids, distance_function)
        new_centroids = update_centroids(data, clusters, k)
        if np.all(centroids == new_centroids):
            break
        centroids = new_centroids
    return clusters, centroids

In [24]:
k = 3  
data_np = data.to_numpy()
clusters, centroids = kmeans(data_np, k, euclidean_distance)

print(clusters)
print(centroids)

[0 1 1 ... 0 1 2]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [25]:
clusters, centroids = kmeans(data_np, k, cosine_distance)

print(clusters)
print(centroids)

[0 1 1 ... 0 1 2]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [26]:
clusters, centroids = kmeans(data_np, k, jaccard_distance)

print(clusters)
print(centroids)

[0 2 1 ... 0 1 2]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [28]:
k = labels[labels.columns[0]].nunique()
k  

10

SSE

In [29]:
def kmeans(data, k, distance_function, max_iters=100):
    centroids = initialize_centroids(data, k)
    for _ in range(max_iters):
        clusters = assign_clusters(data, centroids, distance_function)
        new_centroids = update_centroids(data, clusters, k)
        if np.all(centroids == new_centroids):
            break
        centroids = new_centroids
    # Calculate SSE
    sse = 0
    for i, point in enumerate(data):
        centroid = centroids[clusters[i]]
        sse += distance_function(point, centroid) ** 2
    return clusters, centroids, sse

In [30]:
data_np = data.to_numpy()  # Convert data to numpy array for computation

# Run K-means with Euclidean distance
clusters_euc, centroids_euc, sse_euc = kmeans(data_np, k, euclidean_distance)

# Run K-means with Cosine distance
clusters_cos, centroids_cos, sse_cos = kmeans(data_np, k, cosine_distance)

# Run K-means with Jaccard distance
clusters_jac, centroids_jac, sse_jac = kmeans(data_np, k, jaccard_distance)

# Display the SSE for each method
print("SSE for Euclidean distance:", sse_euc)
print("SSE for Cosine distance:", sse_cos)
print("SSE for Jaccard distance:", sse_jac)

# Determine the best distance metric based on the lowest SSE
best_method = min(('Euclidean', sse_euc), ('Cosine', sse_cos), ('Jaccard', sse_jac), key=lambda x: x[1])
print("Best method based on SSE:", best_method)

SSE for Euclidean distance: 25414767689.9611
SSE for Cosine distance: 686.435572568491
SSE for Jaccard distance: 3660.389493716567
Best method based on SSE: ('Cosine', 686.435572568491)


Accuracy using the majority vote label

In [31]:
from scipy.stats import mode

def majority_vote_labeling(clusters, true_labels, k):
    cluster_labels = np.zeros(k, dtype=int)  # To store the majority label for each cluster
    for i in range(k):
        cluster_points = true_labels[clusters == i]
        if len(cluster_points) > 0:
            cluster_labels[i] = mode(cluster_points).mode[0]  # Majority vote label
    return cluster_labels

def calculate_accuracy(clusters, cluster_labels, true_labels):
    # Predict the label for each point based on its cluster's majority label
    predicted_labels = cluster_labels[clusters]
    accuracy = np.sum(predicted_labels == true_labels) / len(true_labels)
    return accuracy

# Convert labels to numpy array for easier indexing
true_labels = labels[labels.columns[0]].to_numpy()

In [32]:
# Run K-means with Euclidean distance
clusters_euc, centroids_euc, _ = kmeans(data_np, k, euclidean_distance)
cluster_labels_euc = majority_vote_labeling(clusters_euc, true_labels, k)
accuracy_euc = calculate_accuracy(clusters_euc, cluster_labels_euc, true_labels)

# Run K-means with Cosine distance
clusters_cos, centroids_cos, _ = kmeans(data_np, k, cosine_distance)
cluster_labels_cos = majority_vote_labeling(clusters_cos, true_labels, k)
accuracy_cos = calculate_accuracy(clusters_cos, cluster_labels_cos, true_labels)

# Run K-means with Jaccard distance
clusters_jac, centroids_jac, _ = kmeans(data_np, k, jaccard_distance)
cluster_labels_jac = majority_vote_labeling(clusters_jac, true_labels, k)
accuracy_jac = calculate_accuracy(clusters_jac, cluster_labels_jac, true_labels)

# Display the accuracy for each method
print("Accuracy for Euclidean distance:", accuracy_euc)
print("Accuracy for Cosine distance:", accuracy_cos)
print("Accuracy for Jaccard distance:", accuracy_jac)

# Determine the best method based on the highest accuracy
best_accuracy_method = max(('Euclidean', accuracy_euc), ('Cosine', accuracy_cos), ('Jaccard', accuracy_jac), key=lambda x: x[1])
print("Best method based on accuracy:", best_accuracy_method)

C:\Users\world\AppData\Local\Temp\ipykernel_26616\948729412.py:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  cluster_labels[i] = mode(cluster_points).mode[0]  # Majority vote label


Accuracy for Euclidean distance: 0.5851
Accuracy for Cosine distance: 0.6309
Accuracy for Jaccard distance: 0.6021
Best method based on accuracy: ('Cosine', 0.6309)


KMeans with Stop Criteria

In [33]:
import time

def kmeans_with_stop_criteria(data, k, distance_function, max_iters=500):
    centroids = initialize_centroids(data, k)
    prev_sse = float('inf')
    start_time = time.time()
    
    for iteration in range(max_iters):
        clusters = assign_clusters(data, centroids, distance_function)
        new_centroids = update_centroids(data, clusters, k)
        
        # Calculate current SSE
        sse = 0
        for i, point in enumerate(data):
            centroid = centroids[clusters[i]]
            sse += distance_function(point, centroid) ** 2
        
        # Check stopping criteria
        if np.all(centroids == new_centroids):
            print(f"Convergence: No change in centroids at iteration {iteration + 1}")
            break
        if sse > prev_sse:
            print(f"Convergence: SSE increased at iteration {iteration + 1}")
            break
        
        centroids = new_centroids
        prev_sse = sse
    
    end_time = time.time()
    elapsed_time = end_time - start_time
    
    return clusters, centroids, sse, iteration + 1, elapsed_time

In [34]:
# Set up for each distance measure
results = {}

# Run K-means with Euclidean distance
clusters_euc, centroids_euc, sse_euc, iter_euc, time_euc = kmeans_with_stop_criteria(data_np, k, euclidean_distance)
results['Euclidean'] = {'SSE': sse_euc, 'Iterations': iter_euc, 'Time': time_euc}

# Run K-means with Cosine distance
clusters_cos, centroids_cos, sse_cos, iter_cos, time_cos = kmeans_with_stop_criteria(data_np, k, cosine_distance)
results['Cosine'] = {'SSE': sse_cos, 'Iterations': iter_cos, 'Time': time_cos}

# Run K-means with Jaccard distance
clusters_jac, centroids_jac, sse_jac, iter_jac, time_jac = kmeans_with_stop_criteria(data_np, k, jaccard_distance)
results['Jaccard'] = {'SSE': sse_jac, 'Iterations': iter_jac, 'Time': time_jac}

# Display results for each method
for method, result in results.items():
    print(f"{method} Distance - SSE: {result['SSE']}, Iterations: {result['Iterations']}, Time: {result['Time']} seconds")

# Identify the method requiring the most iterations and time
most_iterations = max(results.items(), key=lambda x: x[1]['Iterations'])
most_time = max(results.items(), key=lambda x: x[1]['Time'])

print(f"Method with most iterations: {most_iterations[0]} with {most_iterations[1]['Iterations']} iterations")
print(f"Method with most time: {most_time[0]} with {most_time[1]['Time']} seconds")


Convergence: No change in centroids at iteration 33
Convergence: SSE increased at iteration 29
Convergence: SSE increased at iteration 2
Euclidean Distance - SSE: 25414767689.9611, Iterations: 33, Time: 97.01086235046387 seconds
Cosine Distance - SSE: 686.2292942871771, Iterations: 29, Time: 75.621999502182 seconds
Jaccard Distance - SSE: 4239.94646500194, Iterations: 2, Time: 5.2033586502075195 seconds
Method with most iterations: Euclidean with 33 iterations
Method with most time: Euclidean with 97.01086235046387 seconds


KMeans with Specific stop criteria 

In [35]:
def kmeans_with_specific_stop_criteria(data, k, distance_function, stop_criterion, max_iters=100):
    centroids = initialize_centroids(data, k)
    prev_sse = float('inf')
    for iteration in range(max_iters):
        clusters = assign_clusters(data, centroids, distance_function)
        new_centroids = update_centroids(data, clusters, k)
        
        # Calculate current SSE
        sse = 0
        for i, point in enumerate(data):
            centroid = centroids[clusters[i]]
            sse += distance_function(point, centroid) ** 2
        
        # Apply the specific stop criterion
        if stop_criterion == 'no_change' and np.all(centroids == new_centroids):
            break
        if stop_criterion == 'sse_increase' and sse > prev_sse:
            break
        if stop_criterion == 'max_iter' and iteration + 1 >= max_iters:
            break
        
        centroids = new_centroids
        prev_sse = sse
    
    return clusters, centroids, sse, iteration + 1

In [36]:
# Function to run K-means with all three criteria for a specific distance function
def run_all_criteria(data, k, distance_function, max_iters=100):
    sse_results = {}
    
    # No change in centroid position
    _, _, sse_no_change, _ = kmeans_with_specific_stop_criteria(data, k, distance_function, 'no_change', max_iters)
    sse_results['No Change'] = sse_no_change
    
    # SSE increases
    _, _, sse_increase, _ = kmeans_with_specific_stop_criteria(data, k, distance_function, 'sse_increase', max_iters)
    sse_results['SSE Increase'] = sse_increase
    
    # Max iterations
    _, _, sse_max_iter, _ = kmeans_with_specific_stop_criteria(data, k, distance_function, 'max_iter', max_iters)
    sse_results['Max Iter'] = sse_max_iter
    
    return sse_results


In [37]:
# Run comparisons for each distance metric
sse_comparisons = {
    'Euclidean': run_all_criteria(data_np, k, euclidean_distance, 100),
    'Cosine': run_all_criteria(data_np, k, cosine_distance, 100),
    'Jaccard': run_all_criteria(data_np, k, jaccard_distance, 100)
}

# Display SSE results for each criterion and each distance measure
for metric, sse_results in sse_comparisons.items():
    print(f"{metric} Distance SSE Comparison:")
    for criterion, sse in sse_results.items():
        print(f"  {criterion} criterion SSE: {sse}")

Euclidean Distance SSE Comparison:
  No Change criterion SSE: 25414767689.9611
  SSE Increase criterion SSE: 25414767689.9611
  Max Iter criterion SSE: 25414767689.9611
Cosine Distance SSE Comparison:
  No Change criterion SSE: 686.435572568491
  SSE Increase criterion SSE: 686.2292942871771
  Max Iter criterion SSE: 686.435572568491
Jaccard Distance SSE Comparison:
  No Change criterion SSE: 3660.389493716567
  SSE Increase criterion SSE: 4239.94646500194
  Max Iter criterion SSE: 3660.389493716567
